// errors.ts
export const ErrorCodes = {
  BAD_REQUEST: "BAD_REQUEST",
  SERVER_ERROR: "SERVER_ERROR",
  UPLOAD_ERROR: "UPLOAD_ERROR",
  UPLOAD_NO_FILE: "NO_FILE_PROVIDED",
  ELEMENT_NOT_FOUND: "ELEMENT_NOT_FOUND",
  DUPLICATE_ERROR: "DUPLICATE_ERROR",
  RATE_LIMIT: "RATE_LIMIT_EXCEEDED",
  
  DATABASE_ERROR: "DATABASE_ERROR",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
